### ISSUE TITLE
alwsl and zfs

### ISSUE THREAD

**Issue by tirrorex** [alwsl/alwsl#15]
Hello, i just discovered this project and i am wondering what are the possibilities of it.
I saw that it is possible to run yaourt, will i be able to use it to plug zfs and samba so i can my zfs raid on my windows install?
That would be glorious !
Sorry to bother you with noob question :)

**Comment by turbo** [comment]
I don't understand your question.
- What does running yaourt have to do with zfs?
- What do you mean "can my zfs raid on windows"?

WSL has no notion of file systems. It's a binary call translation. alwsl 1.0 can run on more frameworks than just WSL, and some of them require samba. But the arch file system is going to be ext4 at best.

But all this is guessing, as it's really hard to understand what you actually want to achieve.

**Comment by tirrorex** [comment]
-Yaourt allows to install this aur repo : https://aur.archlinux.org/packages/zfs-linux/
- If i can run zfs on my windows i can mount my zfs pool thus reading my datas.

I just want to run the zfs module on my windows 10 install using this tool if possible, i don't really know how wsl works but i assume it will be possible if i can get the binary with yaourt and run it.

**Comment by turbo** [comment]
Just because it's a packet doesn't mean it's related to yaourt.

Now again, what _is_ your "zfs pool"? Where is this data stored? Windows does not support ZFS, and WSL is not a different operating system. It's still Windows, now running the archlinux userland.

It doesn't have a linux kernel, therefore linux kernel modules (like ZFS) are not supported.

**Comment by tirrorex** [comment]
A zfs pool is a raid managed by zfs.
Data is stored on harddrives.

Well, i can run ext2 or ext4 on windows 10 using software so i assumed wsl with the build included enough to be able to run zfs.
Why would the linux kernel be needed?

**Comment by anaisbetts** [comment]
Because zfs is a Linux kernel module, and unless there is a Linux kernel to plug it into, it's not very useful

**Comment by turbo** [comment]
Exactly.
