### ISSUE TITLE
openssh always opens up an x-window to verify authenticity, but unable to enter password

### ISSUE THREAD

**Issue by ericfont** [alwsl/alwsl#17]
If I try to run a git fetch via ssh or try to ssh to another computer, I get a popup asking for password, but without any way to enter the password:

![screenshot 47](https://cloud.githubusercontent.com/assets/6502474/19018056/6721383a-8821-11e6-88d3-701e8166c53a.png)

so the ssh operation fails.  I've made sure openssh-askpass is uninstalled, but this still happens.

**Comment by turbo** [comment]
Don't report issues for the batchfile (sorry for the previous misunderstanding). See #10
