### ISSUE TITLE
How's alwsl.sfs built?

### ISSUE THREAD

**Issue by ilpianista** [alwsl/alwsl#18]
Thank you a lot for ALWSL, but how's alwsl.sfs built?

Also, why do you include yaourt by default?

**Comment by turbo** [comment]
I intend to document the bootstrapping process that leads to the distro in detail once the .6 dev preview is out. The current version, albeit having over 600 installs already, is not representative of the final version. 

The reason why is also the answer to your second question: Once I had a somewhat stable arch userland running I wanted to package that for distribution through the then-soon-to-be alwsl. I use yaourt personally, so I naturally had it installed already (with some other junk still present in the distro). Now, originally, this repo only had a dev branch. Somehow that went a bit viral (I guess) before I couldn't _even create_ a master branch. I just did so to not confuse people coming from the GitHub trending list, as they would only see an empty repo. 

The base rootfs that's going to be used in future versions is of course much cleaner than this.

**Comment by Krutonium** [comment]
As someone who owns 4 of those installs: Well done.

**Comment by turbo** [comment]
@ilpianista If you want to try the somewhat finished clean rootfs, replace

``` text
https://cdn.turbo.run/alwsl/alwsl.sfs
```

with

``` text
https://cdn.turbo.run/alwsl/bootstrap/alwsl.sfs
```

This should be as clean as possible, not that different from from the mainline bootstrap tarball, yet containing all the WSL fixes. Managed to cut about 50MB of fluff, I'll clean up some more later, but I figured you'd be interested.

**Comment by turbo** [comment]
Actually, lemme push that to main. Seems to work fine.

**Comment by ilpianista** [comment]
Great! Thank you @minxomat!

**Comment by tinytangent** [comment]
Seems it's actually possible to replace the alwsl.sfs image with an official arch linux squashfs image (need to remove some bat code too), and perform some manual adjustments afterwards (i.e. fakechroot). So I really hope this issue can be resolved sooner. It's always a bit worrying when the script is actually downloading a non-official binary image.
