### ISSUE TITLE
Launching script in a folder with spaces in the name causes errors in installation

### ISSUE THREAD

**Issue by jmfergeau** [alwsl/alwsl#19]
The installation derps when one of the folders containing the script has spaces (for instance `that folder`) when it attempts to copy the rootfs to the temporary extraction destination. 

In that case, the script expects `/mnt/c/that` and `folder/alwsl.sfs` separately (and fails since it obviously can't find them) instead of `/mnt/c/that folder/alwsl.sfs`.

In case anybody runs into the same problem, just put the script in another place that hasn't any spaces in the name (like C:\temp or anywhere )

**Comment by turbo** [comment]
Please do not report errors for this preview. See #10 .
