### ISSUE TITLE
Can't install on W10 with admin privileges

### ISSUE THREAD

**Issue by SpencerDoesCode** [alwsl/alwsl#20]
I'm running from cmd with administrator privileges, and get the following:

` alwsl.bat install
alwsl (info): Cleaning old files.
alwsl (info): Installing base lxss fs from trusty server image. This will take A WHILE.
-- Beta feature --
This will install Ubuntu on Windows, distributed by Canonical
and licensed under its terms available here:
https://aka.ms/uowterms

Downloading from the Windows Store...
Unable to download from the Windows Store. Please check your network connection.
alwsl (fail): lxrun failed to install Microsoft's rootfs. Try to restart alwsl again. If this
alwsl (fail): error persists, check your firewall and AV. If all fails, open a GH issue.`

Any assistance to help fix/workaround the issue is gladly appreciated.

**Comment by turbo** [comment]
Multiple problems here:

a) Search the issues before opening a new one. #1 says that alwsl _must no be run as admin_.

b) It says right there what the problem this:

> Downloading from the Windows Store...
> Unable to download from the Windows Store. Please check your network connection.

This is an error thrown by the Windows tool, not alwsl. There's nothing I can do about this. Update your system, check your internet connection.
