### ISSUE TITLE
posix_spawn failed: Operation not permitted

### ISSUE THREAD

**Issue by Rikarin** [alwsl/alwsl#23]
Hello,
When I try to compile and then link software through the ldc compiler it thrown me this error:

```
Error: /usr/sbin/ar failed with status: -1
Error: message: posix_spawn failed: Operation not permitted
```

**Comment by turbo** [comment]
This is not really helpful on it's own. Please create a self-contained example so I can reproduce this.

**Comment by mati865** [comment]
Run as root:

```
touch test.c
clang test.c
```

**Comment by turbo** [comment]
Duplicate of #33 .
