### ISSUE TITLE
B A T C H   R E C U R S I O N  exceeds STACK limits

### ISSUE THREAD

**Issue by starks** [alwsl/alwsl#24]
The script cuts out towards the end.

Parallel unsquashfs: Using 8 processors
28331 inodes (26391 blocks) to write

[===================================================================
created 22909 files
created 1928 directories
created 3640 symlinks
created 8 devices
created 0 fifos
*****\*  B A T C H   R E C U R S I O N  exceeds STACK limits ******
Recursion Count=301, Stack Usage=90 percent
*****\*       B A T C H   PROCESSING IS   A B O R T E D      ******

**Comment by turbo** [comment]
Do not report Errors for this version. See #10 .
