### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by hazzino** [alwsl/alwsl#26]
*****\*  B A T C H   R E C U R S I O N  exceeds STACK limits ******
Recursion Count=301, Stack Usage=90 percent
*****\*       B A T C H   PROCESSING IS   A B O R T E D      ******
Any idea

**Comment by turbo** [comment]
Search issues before posting a new one. See #24 . Read https://github.com/turbo/alwsl/issues/10#issuecomment-247330534
