### ISSUE TITLE
Error: 0x80070002

### ISSUE THREAD

**Issue by mathisen99** [alwsl/alwsl#27]
i only getting this error when trying to use this.. 
worked great like 2 - 3 weeks ago..

**Comment by mathisen99** [comment]
Solved! it seem it dont respect spaces in user names.. i had "name name" in c:\users needed to run the .bat from c:\ and it worked...

**Comment by turbo** [comment]
Refer https://github.com/turbo/alwsl/issues/10#issuecomment-247330534
