### ISSUE TITLE
Sorry for batch 

### ISSUE THREAD

**Issue by hazzino** [alwsl/alwsl#29]
Having after reading all the info inherent to the 
PS C:> .\alwsl.bat install
alwsl (info): Cleaning old files.
alwsl (info): Installing base lxss fs from trusty server image. This will take A WHILE.
-- Beta feature --
This will install Ubuntu on Windows, distributed by Canonical
and licensed under its terms available here:
https://aka.ms/uowterms

Downloading from the Windows Store... 100%
Extracting filesystem, this will take a few minutes...
Installation successful!
alwsl (info): Downloading alwsl rootfs (this might take a while)...
alwsl (info): Downloading checksum for this image.
alwsl (info): Checksums match :-)
alwsl (info): Copying rootfs to temporary extraction destination.
alwsl (info): Unsquashing rootfs.
Parallel unsquashfs: Using 8 processors
24803 inodes (22681 blocks) to write

[==================================================================================================| ] 22578/22681  99%
created 19400 files
created 1720 directories
created 3611 symlinks
created 11 devices
created 0 fifos
*****\*  B A T C H   R E C U R S I O N  exceeds STACK limits ******
Recursion Count=301, Stack Usage=90 percent
*****\*       B A T C H   PROCESSING IS   A B O R T E D      ******

with the windows firewall of download it broked while Fw on gives me same error no diff with admin or users.Running on windows 10 Preview 149436

**Comment by Rikarin** [comment]
I have the same problem.
https://github.com/turbo/alwsl/issues/10

Next monday will be released new version?!

**Comment by minxomat** [comment]
Yes

**Comment by turbo** [comment]
If you want to know what caused this (this isn't really relevant, but it might satisfy your curiosity): This occurs on low-end CPUs or on slower Drives (also SSDs were Garbage-Collection kicks in). The routine waits for the LXSS manager to make a graceful exit. If that doesn't happen within the stack limits of the console host interpreter, it crashes.
