### ISSUE TITLE
Ask to install X

### ISSUE THREAD

**Issue by turbo** [alwsl/alwsl#3]
alwsl is auto-configured to use X if available. Improvement: Ask user during install if they want to install XMing.

Security concerns:

Sourceforge is notorious for packaging adware. Pull XMing from the Turbo CDN (same place where the rootfs is fetched already).

**Comment by sylveon** [comment]
What about VcXsrv users?

**Comment by turbo** [comment]
Sorry for the delay. The new version does have a plugin system (kinda like PKGB, but on the Windows side). The Xming plugin is supplied by me (and supported). Other users can create plugins for other X servers. Business is crazy right now, so the next update will be a bit delayed.

**Comment by turbo** [comment]
Done in private dev branch.
