### ISSUE TITLE
404 on any pacman installation attempt

### ISSUE THREAD

**Issue by moutonnoireu** [alwsl/alwsl#35]
Here : 

![](https://i.imgur.com/JZSrGa6.png)

Did test with 3 up to date repository, http/https. :(

**Comment by turbo** [comment]
Did you update (pacman -Syy) before attempting to install zsh?

**Comment by moutonnoireu** [comment]
I did not. I'm feeling like a dumb dumb now. Thank you !

**Comment by coderobe** [comment]
Note: **never** update using pacman -Sy alone.  
http://gist.io/5660494
