### ISSUE TITLE
can i see which step is being of the process?

### ISSUE THREAD

**Issue by ymfsing** [alwsl/alwsl#36]
#I just push the bat file to the cmd.exe to run this,i don't it's ok?
And as known，it's slow to visit the site in china，even if the global agent is opening.
So i want to know which step is being and how long it will take.
Sorry for bothering,maybe stupid.
Thanks.

**Comment by Jesskas** [comment]
Try specifically running cmd.exe as administrator, if you aren't already - not running it as administrator and executing the .bat seems to produce no output.

**Comment by turbo** [comment]
@Jesskas That is untrue and very dangerous. No part of this batch file or lxrun requires admin rights whatsoever. You should never run anything related to WSL as admin.

**Comment by Jesskas** [comment]
After investigating further, the problem I experienced was related to not actually using cmd.exe directly, which does produce output, and rather using [cmder](https://github.com/cmderdev/cmder) (Which claims to be running cmd.exe in my current session but I guess it isn't.)
