### ISSUE TITLE
install fish shell error

### ISSUE THREAD

**Issue by redapple0204** [alwsl/alwsl#37]
I've tried to install fish shell,but there are some errors in it:
>root@DESKTOP-8DTO912:~# fish
Failed to execute process '/usr/sbin/uname'. Reason:
exec: Invalid argument
switch: Expected exactly one argument, got 0

>/usr/share/fish/functions/__fish_pwd.fish (line 1): switch (uname)
                                                           ^
>from sourcing file /usr/share/fish/functions/__fish_pwd.fish
        called on standard input

>in command substitution
        called on standard input

>in command substitution
        called on standard input

>fish: echo $_ " "; __fish_pwd
                   ^
>in command substitution
        called on standard input

>Failed to execute process '/usr/bin/fish'. Reason:
exec: Invalid argument
Failed to execute process '/usr/sbin/seq'. Reason:
exec: Invalid argument
Failed to execute process '/usr/sbin/seq'. Reason:
exec: Invalid argument
Failed to execute process '/usr/sbin/seq'. Reason:
exec: Invalid argument
Failed to execute process '/usr/sbin/hostname'. Reason:
exec: Invalid argument
fish: Unknown command '__fish_pwd'
fish: echo $_ " "; __fish_pwd
                   ^
>in command substitution
        called on standard input

>root@ ~# exit
fish: Unknown command '__fish_pwd'
fish: echo $_ " "; __fish_pwd
                   ^
>in command substitution
        called on standard input

**Comment by jcfeitosa** [comment]
Here too

**Comment by ghost** [comment]
Same here. Returns the following when I try to run it:
```
> fish
fish: ../sysdeps/unix/sysv/linux/spawni.c:360: __spawnix: Assertion `ec >= 0' failed.
Aborted (core dumped)
(ERROR)-(Exit Code 134)-(Fatal error signal 6)
```

**Comment by mati865** [comment]
Possibly it's WSL limitation, maybe someone could test it with Insider build?
Many similar bugs seems to be solved: https://msdn.microsoft.com/en-us/commandline/wsl/release_notes

**Comment by cuevasclemente** [comment]
I can confirm this error as well

**Comment by cuevasclemente** [comment]
Unfortunately, it seems to have the same error in the latest insider build. I'm getting the same error @Pyrepenol got: 
```
root@DESKTOP-T80U6MV:~# fish
fish: ../sysdeps/unix/sysv/linux/spawni.c:360: __spawnix: Assertion `ec >= 0' failed.
Aborted (core dumped)
```

I've attached a picture of the output of winver (sorry, it's in French).
![capture](https://cloud.githubusercontent.com/assets/6854890/24131039/91a3f54e-0dc2-11e7-8951-90650aaf9816.PNG)

**Comment by ghost** [comment]
It seems that this is still an issue on the Creators Update. I have not tried the newest Insider Preview build (16070) but I doubt that's addressed it.

**Comment by turbo** [comment]
This is an upstream issue. Please refer to the above crosslink.
