### ISSUE TITLE
Installation fails if there is a space in username

### ISSUE THREAD

**Issue by jsmcconn** [alwsl/alwsl#38]
alwsl (info): Downloading alwsl rootfs (this might take a while)...
alwsl (info): Copying rootfs to temporary extraction destination.
cp: cannot stat ‘/mnt/c/Users/First’: No such file or directory
cp: cannot stat ‘Last/Downloads/alwsl/alwsl.sfs’: No such file or directory
alwsl (info): Unsquashing rootfs.
alwsl (info): Transforming...
        1 dir(s) moved.
        1 dir(s) moved.
        1 dir(s) moved.
Error: 0x80070002
alwsl (info): Checking installation success...
alwsl (fail): Installation failed. Bash is still ubuntu. Try again.

Fixable with:
-bash -c "cd && mkdir -p rootfs-temp && cd rootfs-temp && cp %mountpoint% ."
+bash -c "cd && mkdir -p rootfs-temp && cd rootfs-temp && cp \\"%mountpoint%\\" ."

**Comment by turbo** [comment]
Submit a PR please.
