### ISSUE TITLE
status

### ISSUE THREAD

**Issue by coderobe** [alwsl/alwsl#39]
is this project dead? README.md states that a new version will be ready in "a few days"

**Comment by turbo** [comment]
No it isn't. I'm currently waiting on a contract for a more stable delivery of future updates and rootfs. If the sponsor I'm negotiating right now comes through, a new version will be released.

Until then, the current version should work as it always did.

I know it's taken a long time, and the holidays added even more delay, but stay tuned.

**Comment by crutchcorn** [comment]
Word of note; I'd avoid saying things as you had here in the future @coderobe. Asking if a project is dead and reminding/asking for deadlines on an open source project (especially a personal one as this) is in bad taste, and will get you banned from many a community I could name. There are ways of asking about the status of a project that might be better suited in the future, be sure to look out for them

**Comment by turbo** [comment]
@crutchcorn Please do not speak for this project. If I would have had any issue with the way they asked for the project status, I would have said so. 

In fact, your comment is even less constructive, because you just criticize them and don't actually comment on what you think would be a more suitable way to ask.

Also, this is a *very* common way to ask for "dead" projects. [A simple search for such issues](https://www.google.com/search?q=site%3Agithub.com+intitle%3Aissue+"is*dead") gives more than 46k results.

**Comment by crutchcorn** [comment]
I apologize. Wasn't trying to speak on behalf of the project, usually add a disclaimer on something like that, but hadn't this time. 

Those are fair points (I'd argue the commonality, but I digress) and something I should note next time. I'm seeing my attitude and apologize, been a hard week.

**Comment by coderobe** [comment]
@crutchcorn i wasn't asking for any deadline, just wanted some info on the current status because there were no commits in a while & the readme stated there should be some by now. i'm not trying to push for a release or anything - it just seemed like development kinda stalled.

@turbo thanks for the info, let's hope for the best 👍

**Comment by piranna** [comment]
> I'm currently waiting on a contract for a more stable delivery of future updates and rootfs. If the sponsor I'm negotiating right now comes through, a new version will be released.

I'm interested on this topic from a personal point of view, I always has problems finding sponsors for my own projects (I don't have the marketing and speech skills for that...). Congrats dude :-)

**Comment by turbo** [comment]
@piranna Generally goes like this:

- Find companies that sponsor FOSS development
- Asses your needs
- Collect objective usage data on what resources you need and how much that'll grow in the future
- Write in and be patient
- Be prepared to be rejected and thank them anyway if it happens
