### ISSUE TITLE
BITSAdmin Error And Renaming Shortcut Endless

### ISSUE THREAD

**Issue by Lykaksparsz** [alwsl/alwsl#41]
https://gyazo.com/dee3eb1e0bfc96c7de9cf0c2015cc44f
```
Unable to complete job - 0x80200002
The requested action is not allowed in the current job state. The job is read-only. The job may have been canceled or c
```

**Comment by novatech** [comment]
it seem that https://cdn.turbo.run/alwsl/archlinux.ico does not exists anymore. bitsadmin freeze when try to download it and caused the endless renaming shortcut. you can comment out line 202 or use following command to cancel the download. bitsadmin /cancel alwsl

**Comment by turbo** [comment]
The new url is https://antiquant.com/alwsl/archlinux.ico. I'll update.

**Comment by tiexo** [comment]
I downloaded the latest version of the bat file, but it still worked in renameing shortcut, and finally I canceled the order. @turbo 

![](https://cloud.githubusercontent.com/assets/8164505/25781706/9039e92a-336f-11e7-8e9b-652e6371b1f0.PNG)

**Comment by xDShot** [comment]
It's broken again. Installing hangs on `alwsl (info): Renaming shortcut.`
