### ISSUE TITLE
Cant connect to internet.

### ISSUE THREAD

**Issue by OctoNezd** [alwsl/alwsl#42]
Pacman fails with connection time out, and every other thing too.

**Comment by turbo** [comment]
Can't repro this on a clean Win10.

**Comment by tehbilly** [comment]
Are you behind a proxy? Does the base wsl setup work for you?

**Comment by OctoNezd** [comment]
I am not behind a proxy, base wsl setup work just fine

**Comment by turbo** [comment]
Make a screenshot of the pacman command failing. 

You did update the package list though ( #35 ), right?

**Comment by turbo** [comment]
Closed until further info is supplied.

**Comment by arbv** [comment]
Dear minxomat,

The email sent to artem@artlabs.tk with subject
"Re: [alwsl/alwsl] Cant connect to internet. (#42)"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to artem@artlabs.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/

**Comment by turbo** [comment]
> Looking for a way to Protect Your Identity and for a great no-more-spam solution for your email

How is that supposed to be a no spam solution if this utterly useless message is posted here and also sent to me vial email. Using this will be a quick way to get kicked from participating in issue trackers of projects I'm on.

**Comment by OctoNezd** [comment]
![image](https://cloud.githubusercontent.com/assets/15308404/22020714/cc28c308-dcca-11e6-8a68-7e2bf63ef4cb.png)

**Comment by turbo** [comment]
- **Did** you update the package list first?
- Did you modify the repo list to choose kernel.org? If so, can you try a different repo?
- Can you resolve mirrors.kernel.org (`curl -I mirrors.kernel.org`)?

**Comment by turbo** [comment]
Repro status:

- Cannot repro on Windows 10 Enterprise Build 14986
- Cannot repro on Windows 10 Enterprise Build 15002

**Comment by xDShot** [comment]
Try changing repo mirror.

**Comment by turbo** [comment]
Cannot reproduce. Feel free to discuss this further nonetheless.

**Comment by plotnw** [comment]
I am also getting this issue, pacman  fails to download from any mirrors, and `curl -I mirrors.kernel.org` times out as well. 

I am on Build16170.rs_prerelease170331-1532 of windows 10 (10.0.16170 Build 16170)

When I had previously installed normal wsl, installing packages and ping worked. 

[2017-04-12 14_28_39-select root plotnwtab_ _etc_pacman d](https://cloud.githubusercontent.com/assets/14968011/24973340/63635676-1f8c-11e7-8d61-588b92e5cbca.png)
