### ISSUE TITLE
Arrow keys don't work

### ISSUE THREAD

**Issue by Antioch18** [alwsl/alwsl#47]
After clean installing alwsl I found that the arrow keys don't work in Arch. For example, I can't use left/right to move the text edit location on the command line.

This was found when using bash in ConEmu. Note that the same issue didn't exist when using the standard Ubuntu WSL in ConEmu.

**Comment by autoferrit** [comment]
I have the same issue as well. It also means I am unable to use up/down to traverse command history as well.

**Comment by turbo** [comment]
> This was found when using bash in ConEmu. Note that the same issue didn't exist when using the standard Ubuntu WSL in ConEmu.

Yes it does. This is not related to alwsl, but how bash.exe hosts the console. ConEmu does not integrate this mode, it simply fakes the window (the same thing happens if you use PuTTY in ConEmu). See #25 .
