### ISSUE TITLE
Error: /proc must be mounted

### ISSUE THREAD

**Issue by fg-dev** [alwsl/alwsl#49]
After installing archilinux
whene i run "ps" i get :

Error: /proc must be mounted
  To mount /proc at boot you need an /etc/fstab line like:
      proc   /proc   proc    defaults
  In the meantime, run "mount proc /proc -t proc"

**Comment by redapple0204** [comment]
me too

**Comment by godlikemouse** [comment]
Same here, looking for a way to fix that.  I've tried putting the mount commands in both fstab as well as in the .bash_profile but neither appear to work.

**Comment by godlikemouse** [comment]
As a follow up, I can see that /proc is actually mounted:

```
# mount
rootfs on / type rootfs (rw,relatime)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,noexec,relatime,size=204320k,mode=755)
none on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
none on /run/shm type tmpfs (rw,nosuid,nodev,relatime)
none on /run/user type tmpfs (rw,nosuid,nodev,noexec,relatime,size=102400k,mode=755)
```

**Comment by ilpianista** [comment]
This has been fixed _automagically_ for me after last WSL update. I assume this is a duplicate of Microsoft/BashOnWindows#105

**Comment by turbo** [comment]
Upstream issue.
