### ISSUE TITLE
tips for updating

### ISSUE THREAD

**Issue by azapicoe** [alwsl/alwsl#50]
hi, first of all, this is an awesome Project so thanks to the autor.
when i run a pacman -Syu it ask me if i wanna overwrite something with dbus.. i say no but then it dont upgrade anything, whats the correct procedure to upgrade? thanks

**Comment by turbo** [comment]
Hi @azapicoe, thanks for your comment.

You can overwrite and upgrade everything. Packages that must not be overwritten are ignored by pacman. So if pacman asks you

```text
package ... is in the ignore group, upgrade?
```

answer no. Otherwise you can upgrade any package like on a normal archlinux installation.

Cheers.

**Comment by azapicoe** [comment]
ok turbo, thanks for all. and wish you luck with the partners searching.
now im gonna see if i can configure a pulseaudio client-server with Windows (do you know any good guide?) haha
