### ISSUE TITLE
new update breaks pacman

### ISSUE THREAD

**Issue by tek-aevl** [alwsl/alwsl#51]
ca-certificates-utils 20170307-1 upgrade requires manual intervention

2017-03-15

The upgrade to ca-certificates-utils 20170307-1 requires manual intervention because a symlink which used to be generated post-install has been moved into the package proper.

As deleting the symlink may leave you unable to download packages, perform this upgrade in three steps:

# pacman -Syuw                           # download packages
# rm /etc/ssl/certs/ca-certificates.crt  # remove conflicting file
# pacman -Su                             # perform upgrade

[code]
# pacman -Syyu
:: Synchronizing package databases...
error: failed retrieving file 'core.db' from mirrors.kernel.org : error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
error: failed to update core (download library error)
error: failed retrieving file 'extra.db' from mirrors.kernel.org : error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
error: failed to update extra (download library error)
error: failed retrieving file 'community.db' from mirrors.kernel.org : error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
error: failed to update community (download library error)
error: failed to synchronize all databases
[/code]

**Comment by Krutonium** [comment]
(This is also an issue on normal Arch)

**Comment by tek-aevl** [comment]
yes, i discovered that if you run the steps, then reboot host machine the wsl worked as expected afterwards.

**Comment by grwn** [comment]
Rebooting the host didn't work for me. Running "trust extract-compat" did.

**Comment by raphael-costa** [comment]
If this also happens on regular Arch on Linux then this issue should be closed.

**Comment by tehbilly** [comment]
The issue doesn't happen for me with the regular distro, unsure what's causing the `tls-ca-bundle.pem` file from not being present (haven't looked into it is all!), but a quick fix that I got working with alwsl was to modify the official instructions to the following:
``` bash
$ pacman -Syuw                                  # download packages
$ mv /etc/ssl/certs/ca-certificates.crt{,.bak}  # backup conflicting file
$ pacman -Su                                    # perform upgrade
$ mv /etc/ssl/certs/ca-certificates.crt{.bak,}  # restore conflicting file
```
Another option is to not update ca-certificates-utils, of course. If I get time, I'll try to find out why the pem isn't extracted on alwsl.

**Comment by unixfox** [comment]
Please close this issue because it's related to ArchLinux and not to alwsl: https://www.archlinux.org/news/ca-certificates-utils-20170307-1-upgrade-requires-manual-intervention/

**Comment by turbo** [comment]
Closing as upstream issue.
