### ISSUE TITLE
How to update pacman, fakeroot and other customized packages?

### ISSUE THREAD

**Issue by Kimi-Arthur** [alwsl/alwsl#53]
As I read in another issue, alwsl is providing a customized version of pacman.

If pacman is updated, and I assume alwsl will have a corresponding version some time later. How can I update them?

Even manually replacing the binaries will do for me. But I haven't found those binaries (only a rootfs used in the .bat file), so wondering what's your suggested way of updating those packages.

Thanks!

**Comment by turbo** [comment]
These packages are considered stable until there is a major change. fakeroot and others are bypassed. The alwsl system is root by default (which has no effect on the Windows system). I'm investigating how to maybe keep fakeroot around.

However, later these packages will be replaced by alwsl-targeted ones in AUR - except for pacman, where I'm still testing how to best streamline the upgrade process.
