### ISSUE TITLE
systemctl & pacman issues

### ISSUE THREAD

**Issue by mathisen99** [alwsl/alwsl#58]
is systemctl not working at all ? i need a service to run but cant...
"Failed to connect to bus: No such file or directory"

also latest updates breaks pacman due to openssl 1.1 update. , not talking about the cert error.

"pacman: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory"

**Comment by toXel** [comment]
I also have the libcrypto problem with pacman. I've tried to update pacman but that just breaks it. (Yea I know that pacman is in HoldPkg 😉)

**Comment by turbo** [comment]
Will do a repack + recompile. Bit swamped at the moment.

**Comment by godlikemouse** [comment]
Hey guys, a work around fix for this (I just had the same problem) is to run:

`ln -s /usr/lib/libcrypto.so /usr/lib/libcrypto.so.1.0.0`

**Comment by navigaid** [comment]
@godlikemouse installing `openssl` would generate `/usr/lib/libcrypto.so.1.0.0` for you

**Comment by patrickelectric** [comment]
You need to create the symbolic link with like @godlikemouse said.
Maybe it's necessary to do the same thing with openssl.
Than just update your system with `pacman -Syu`

**Comment by turbo** [comment]
Fixed by release.
