### ISSUE TITLE
Building OpenRCT2: lib32-sdl2_ttf unable to build

### ISSUE THREAD

**Issue by Krutonium** [alwsl/alwsl#6]
> **checking whether we are cross compiling... configure: error: in `/tmp/yaourt-tmp-root/aur-lib32-sdl2_ttf/src/SDL2_ttf-2.0.14':
> configure: error: cannot run C compiled programs.
> If you meant to cross compile, use`--host'.**

**Comment by turbo** [comment]
Why are you using lib32? Are you trying to run WSL with multilib tools?

**Comment by Krutonium** [comment]
I am using lib32 because I am compiling OpenRCT2 - which does not as of yet actually support building in x64, at least not in a playable state.

**Comment by turbo** [comment]
Did you try it in the stock WSL? If yes, did it work correctly? Multilib is generally a bad idea in (a)wsl, but maybe we can get this to work somehow.

**Comment by Krutonium** [comment]
It's impossible to build in WSL due to Ubuntu 14.04 being too old.

**Comment by turbo** [comment]
I've only ever did a few tests of 32bit libs and multilib in general on alwsl. I very much doubt that even if it gets beyond the checking it would build. I encountered random and completely inexplicable errors with multilib (like m4 throwing unclear errors). 32bit code seems to be deeply incompatible with WLS.

I'll investigate, some day. For now: Low priority.

**Comment by Krutonium** [comment]
At least thank you for looking into it to some degree. :+1:

**Comment by Krutonium** [comment]
So since this was posted, OpenRCT2 now builds completely x64, and no longer requires multilib. Shall I close this?
