### ISSUE TITLE
Broken icon link - prevents install from completing

### ISSUE THREAD

**Issue by OddZero** [alwsl/alwsl#65]
Hello,

I ran the install script, but it hangs at the end of the process, displaying _"Renaming shortcut."_

Issue seems to be at line 202: the link to the icon is broken. Substituting it with another (working) link fixes the problem, and makes the script run successfully.

`bitsadmin /RAWRETURN /transfer alwsl /download /priority FOREGROUND "https://antiquant.com/alwsl/archlinux.ico" "%localappdata%\lxss\archlinux.ico"`

Regardless of bugs... Keep up the amazing work!

**Comment by ShayBox** [comment]
Wish I would have checked this before figuring that out for myself...

**Comment by ShayBox** [comment]
If you need a tempfix, replace the link on line 202 with "https://www.shareicon.net/download/2015/09/16/101867_archlinux.ico" from [here](https://www.shareicon.net/archlinux-arch-linux-101867)

It's a pretty trusted icon website, but the creator of the github should put an .ico on this github for it to reference

**Comment by OddZero** [comment]
Yes, I used a different source for the icon myself. I agree that a simple fix would be to just include the icon in the repo, or wherever the main files are sourced from..

**Comment by oblitum** [comment]
Wasted a lot of time in this....

**Comment by zameran** [comment]
Thanks to all. I've managed how to make that thing to work properly. 
@ShayBox you're awesome!
@oblitum yeah, me too :)
I've made some changes. See my pull request here: [Yay](https://github.com/alwsl/alwsl/pull/68)

**Comment by turbo** [comment]
Fixed by release.
