### ISSUE TITLE
libcrypto.so.1.0.0 not found.

### ISSUE THREAD

**Issue by ItsDeadEnd** [alwsl/alwsl#67]
it seems that after following the instructions in the readme, pacman no longer works.

"pacman: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared file: No such file or directory"

**Comment by vnznznz** [comment]
Fixed this with: ` ln -s /usr/lib/libcrypto.so /usr/lib/libcrypto.so.1.0.0` It's probably a bad fix, but it works for me.

**Comment by abjugard** [comment]
The correct solution is to run `pacman -Sy openssl-1.0` prior to installing the latest `openssl` package.

How to fix if you've already made your mistake:

1. Temporarily fix `libcrypto.so.1.0.0`
a. Do it correctly
a.1. Download https://www.archlinux.org/packages/extra/x86_64/openssl-1.0/download/
a.2. `cd /tmp`
a.3. `tar xJf /path/to/openssl-1.0-1.0.2.k-3-x86_64.pkg.tar.xz`
a.4. `cd /usr/lib`
a.5. `ln -s /tmp/usr/lib/libcrypto.so.1.0.0 libcrypto.so.1.0.0`
b. Use the cheat @vinzBad mentioned and link `libcrypto.so.1.1` to `libcrypto.so.1.0.0`
2. Open **two** alwsl terminals
3. In one of them run `pacman -Sy openssl-1.0` but **do not** complete the install yet
4. In the **other** terminal, run `rm /usr/lib/libcrypto.so.1.0.0`
5. Complete the installation of `openssl-1.0` in the other terminal window

**Comment by evilhamsterman** [comment]
Regardless of the "correct solution" this shouldn't happen to start with. There is no warning to tell people to update openssl prior to upgrading and openssl should upgrade properly like it does in a regular install. The big question is why it isn't upgrading.

**Comment by turbo** [comment]
I'm currently testing a new image and I'll let it propagate to the CDN today if everything works. So far it seems fine.

**Comment by turbo** [comment]
Fixed by release.
