### ISSUE TITLE
can not generate locale

### ISSUE THREAD

**Issue by hotleave** [alwsl/alwsl#72]
Error occured when i execute `sudo locale-gen`:

```
Generating locales...
  en_US.UTF-8...localedef: ../sysdeps/unix/sysv/linux/spawni.c:366: __spawnix: Assertion `ec >= 0' failed.
/usr/sbin/locale-gen: line 41:   605 Aborted                 (core dumped) localedef -i $input -c -f $charset -A /usr/share/locale/locale.alias $locale
```

**Comment by sunjoong** [comment]
@hotleave - Quote from https://github.com/alwsl/alwsl/issues/33#issuecomment-305159463;
> I've fixed this problem with spawn by backing out the change in glibc mentioned here Microsoft/BashOnWindows#1878
The package is available on the AUR here: https://aur.archlinux.org/packages/glibc-wsl/
You need to build it on a system that already has a working glibc, e.g. a proper linux install.

**Comment by hotleave** [comment]
OK, thank you for your work

**Comment by sunjoong** [comment]
@hotleave - That work was from @patstew :)
