### ISSUE TITLE
pacman stops working after upgrading Win10 to build 16237

### ISSUE THREAD

**Issue by DDoSolitary** [alwsl/alwsl#73]
pacman has the same behavior as that mentioned in https://wiki.archlinux.org/index.php/Pacman/Restore_local_database after upgrading Windows.

> `pacman -Q` gives absolutely no output, and `pacman -Syu` erroneously reports that the system is up to date.
> When trying to install a package using `pacman -S package`, and it outputs a list of already satisfied dependencies.

Any ideas please?

**Comment by sunjoong** [comment]
@DDoSolitary - New issue https://github.com/Microsoft/BashOnWindows/issues/2310 was opened just now, I found; That looks like similar to this, I think.

**Comment by DDoSolitary** [comment]
@sunjoong Thank you for the information. It seems to be the same problem. I'll subscribe to that issue.

**Comment by DDoSolitary** [comment]
It is a regression on the WSL side and has been fixed.
