### ISSUE TITLE
downloading rootfs freezes 

### ISSUE THREAD

**Issue by pasteley** [alwsl/alwsl#80]
There is no network activity for around 10 minutes on "alwsl (info): Downloading alwsl rootfs (this might take a while)..." stage.
Even with administrator privileges.

**Comment by turbo** [comment]
Cannot reproduce from multiple locations.

**Comment by pasteley** [comment]
![capture](https://user-images.githubusercontent.com/1609081/29988002-a9c24882-8f73-11e7-8ec5-5165cb9fe9a4.PNG)

**Comment by pasteley** [comment]
Sniffed with wireshark and last session, that I got is so (no new tcp/udp sessions after this):
```
GET /ubuntu/pool/main/l/lzo2/liblzo2-2_2.06-1.2ubuntu1.1_amd64.deb HTTP/1.1
Host: archive.ubuntu.com
User-Agent: Debian APT-HTTP/1.3 (1.0.1ubuntu2)
```

**Comment by pasteley** [comment]
Please recheck, I would like to provide any info

**Comment by turbo** [comment]
Try downloading the file manually.

**Comment by pasteley** [comment]
I just used [WSL Distribution Switcher](https://github.com/RoliSoft/WSL-Distribution-Switcher) with built-in docker hub pull
