### ISSUE TITLE
sudo: policy plugin failed session initialization

### ISSUE THREAD

**Issue by daihao42** [alwsl/alwsl#82]
Something wrong with sudo, I update my arch on wsl today(2017/09/13) and I get this error when use sudo.
`sudo -i`
`sudo: getrlimit: Function not implemented`
`sudo: setrlimit: Function not implemented`
`sudo: setrlimit: Function not implemented`
`sudo: pam_open_session: Critical error - immediate abort`
`sudo: policy plugin failed session initialization`

and I find that 
`warning: fakeroot: ignoring package upgrade (1.21-2 => 1.22-1)`
`warning: pacman: ignoring package upgrade (5.0.1-4 => 5.0.2-2)`
when Syyu.
Otherwise there is no warning in my another arch on PC.

**Comment by turbo** [comment]
The warnings are by design, this keeps the alwsl-patched pacman alive.

The other missing implementations seem like missing syscalls, not really something I think alwsl could be responsible for.

**Comment by daihao42** [comment]
I see , thank u anyway , I'll try to find some other help

**Comment by simepy** [comment]
@daihaovigg have you find a solution ? i have the same problem with many software
